### ISSUE TITLE
Прописал правила - но бот игнорит.

### ISSUE THREAD

**Issue by burov0798** [follower90/php-vkbot#1]
['operation' => 'equals', 'in' => 'привет', 'out' => 'пока)', 'users' => '339190723', 'chats' => '135'],
	['operation' => 'contains', 'in' => '/тест', 'out' => '/ответ)', 'users' => '339190723', 'chats' => ''],
Бот игнорит,в консоли пишет тип нет правил таких

**Comment by follower90** [comment]
в users, id пользователей, на которых срабатывает правило . в chats id бесед

**Comment by follower90** [comment]
P.S. код обновлён, сделал webUI управление (beta) и настройку правил в sqllite.

**Comment by burov0798** [comment]
Можно с тобой списаться в вк\скайпе?

**Comment by follower90** [comment]
Ок

**Comment by burov0798** [comment]
Ак можно ссылки получить? :D

**Comment by follower90** [comment]
follower.od в skype
